import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import "./globals.css"
import '@mantine/core/styles.css';

import { ColorSchemeScript, MantineProvider } from '@mantine/core';
import { TrpcProvider } from '@/trpc/TrpcProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript/>
      </head>
      <body className={inter.className}>
        <MantineProvider>
          <TrpcProvider>
            {children}
          </TrpcProvider>
        </MantineProvider>
      </body>
    </html>
  )
}
